### ISSUE TITLE
SocialButtons plugin has strange behaviour with this theme

### ISSUE THREAD

**Issue by NunoPinho** [hibbitts-design/grav-theme-quark-open-publishing#18]
Hi,

I'm using this theme to build my companies blog, I need to have the ability to share posts in social media, so I installed SocialButtons plugin, the normal behavior is for example:
1. I choose to share in Facebook
2. It opens a popup, in that popup I can login into Facebook an then edit the description and stuff like that

However in this theme it also opens in the same window, the user would get 2 windows with the same thing and I only want the popup.

It must be something in the theme because I have another site made with Grav with another theme where I installed the plugin and it worked like expected.

Thanks,
Nuno Pinho

**Comment by paulhibbitts** [comment]
Hi @NunoPinho , I've had a look at this Plugin and tested it with Grav's core Quark theme and the issue is there too (Quark is the parent theme for my theme as well). As this Plugin has not been updated in 3 years that might be an issue too (Quark was not around then).

Unfortunately I would not be able to undertake the work required to get this going for you, but of course you are welcome to have someone else take it on if possible. Perhaps there might also be another more current Grav Plugin that offers some of the same functionality?

**Comment by NunoPinho** [comment]
Hi @paulhibbitts , I might be able to afford to spend some time taking a closer look at it, if I discover a solution I will post it here.
Thank you

**Comment by paulhibbitts** [comment]
Sounds good @NunoPinho , thanks very much.
